routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test/Adomicile', 'Adomicile@index');
Route::get('/test/Check', 'Check@index');
Route::get('/test/Transfer', 'Transfer@index');


Route::get('/valide/{id}', 'Adomicile@update');
Route::post('/test/send', 'EmailController@send')->name('Admin.mail');
Route::get('admin/sendbox', 'EmailController@show')->name('Admin.send.mail');
Route::get('admin/sendbox/{Email}', 'EmailController@showmail');
Route::get('admin/trash', 'EmailController@showtrash')->name('Admin.trash');
Route::get('admin/destroy/{Email}', 'EmailController@destroy');
Route::get('admin/chat/', 'EmailController@chat')->name('chat.index');



Route::post('/test/payer', 'ProductsController@payer')->name('payer');

Route::get('/test/Strip', 'Strip@index');
Route::post('/charge','strip@charge');

Route::get('/test/Paypal', 'Paypal@paypal');
Route::get('/status', 'Paypal@status')->name('status');
Route::get('/canceled', 'Paypal@canceled')->name('canceled');

Route::get('/test', 'ProductsController@index');

Route::get('show/{id}','ProductsController@show')->name('store.show');
Route::get('cart', 'ProductsController@showCart')->name('cart');
Route::get('add-to-cart/{Product}', 'ProductsController@addToCart')->name('cart.add');;
Route::patch('update-cart', 'ProductsController@update');

Route::delete('remove-from-cart', 'ProductsController@remove');



Route::get('fr','web\fr\IndexController@index')->name('web.fr.index');
Route::get('de','web\de\IndexController@index')->name('web.de.index');
Route::get('en','web\en\IndexController@index')->name('web.en.index');

Route::get('products/{id}','ProductsController@products_seo')->name('products.seo');

Route::get('animation_caroucel', 'Animation@animation_caroucel');
Route::get('story', 'Animation@story');

Route::get('animation', 'Animation@index');
Route::get('animation_slider', 'Animation@slider');
Route::get('animation2', 'Animation@index2');
Route::get('animation3', 'Animation@index3');
Route::get('animation4', 'Animation@index4');
Route::get('animation5', 'Animation@index5');
Route::get('animation6', 'Animation@index6');
Route::get('animation7', 'Animation@index7');

Route::get('testcart', 'ProductsController@testcart');
Route::get('testcartlist', 'ProductsController@testcartlist')->name('testcartlist');

Route::get('change/{id}', 'ProductsController@listproduitdollar')->name('home.store.dolar');
Route::get('/', 'ProductsController@listproduit')->name('index.store');
Route::get('home', 'ProductsController@listproduit')->name('home.store');
Route::get('electronics', 'ProductsController@listproduit')->name('store.electronics');
Route::get('women', 'ProductsController@listproduit')->name('store.women');
Route::get('men', 'ProductsController@listproduit')->name('store.men');
Route::get('shop', 'ProductsController@listproduit')->name('store.shop.all');



Route::get('checkbox', 'MemberController@index')->name('checkbox.index');
Route::get('createposts', 'MemberController@create');
Route::post('store', 'MemberController@store');
Route::resource('checkbox', 'MemberController');

Route::get('checkboxtable','FrontpageController@home');
Route::post('/orders','OrderController@store');
Route::get('/orders','OrderController@index');
Route::post('store', 'OrderController@store')->name('order.store');
Route::get('/items/{id}','OrderController@items');

Route::get('/cart/details','user\CartdetailsController@index')->name('cart.details.user');
Route::post('/cart/details','user\CartdetailsController@edit')->name('cart.details.user.save');

Route::get('/cart/delivery/{id}','user\CartdeliveryController@index')->name('cart.delivery.user');
Route::post('/cart/delivery/{id}','user\CartdeliveryController@edit')->name('cart.delivery.user.save');



Route::get('/cart/payment/{id}','user\PaymentController@index')->name('cart.payment.user');
Route::post('/cart/payment/{id}','user\PaymentController@edit')->name('cart.payment.user.save');


Route::get('cart/login', 'UserLoginStoreController@index')->name('login.store');
Route::post('cart/login', 'UserLoginStoreController@postLogin')->name('user.login.store.save'); 

Route::get('login', 'UserLoginController@index')->name('login');
Route::post('login', 'UserLoginController@postLogin'); 

//registration routes
Route::get('registration', 'UserLoginController@registration')->name('user.registration');
Route::post('registration', 'UserLoginController@store')->name('user.registration.save'); 
Route::get('registrationedite', 'UserLoginController@registrationedite');
Route::post('registrationedite', 'UserLoginController@postregistrationedite'); 

//dashboard and logout route
Route::middleware('auth')->group(function(){
    Route::get('user', 'user\UserController@dashboard'); 
    Route::get('user/dashboard', 'user\UserController@dashboard')->name('user.dashboard'); 
    Route::get('user/profile', 'UserLoginController@profile')->name('user.profile');
    Route::get('user/logout', 'UserLoginController@logout');
    });
    
Route::get('user/request','user\OrderController@index')->name('user.request');
Route::get('user/request/show/{id}','user\OrderController@showrequest')->name('user.request.show');
Route::get('user/address', 'user\UserController@address')->name('user.address');

Route::get('user/edit','user\UserController@show')->name('user.edit');
Route::post('user/edit','user\UserController@edit')->name('user.edit.save');
Route::get('user/setting', 'user\UserController@setting')->name('user.setting'); 
Route::get('user/setting/change-password', 'user\ChangePasswordController@index')->name('change.password.view');
Route::post('user/setting/change-password', 'user\ChangePasswordController@store')->name('change.password');	
	
Route::get('user/setting/pic','user\PhotoController@show')->name('change.pic.view');
Route::post('user/setting/pic','user\PhotoController@edit')->name('change.pic');
	
Route::get('admin/stape1', 'AdminLoginController@stape1')->name('login.admin.stape1');

Route::get('admin', 'AdminLoginController@index')->name('login.admin');
Route::post('admin/varification', 'AdminLoginController@stape2')->name('login.admin.stape2');
	
Route::get('admin', 'AdminLoginController@index')->name('login.admin');
Route::post('admin', 'AdminLoginController@postLogin')->name('saveadminlogin'); 


Route::middleware('auth')->group(function(){
Route::get('admin/home', 'admin\AdminController@dashboard')->name('home'); 
Route::get('admin/homes', 'admin\AdminController@dashboards')->name('homes'); 


Route::post('admin/logout', 'AdminLoginController@logout')->name('logout'); 
});
//Admin profile
Route::get('admin/profile', 'admin\ProfileController@profile')->name('admin.profile');
Route::get('admin/profile/edit','admin\ProfileController@show')->name('admin.edit.profile');
Route::post('admin/profile/edit','admin\ProfileController@edit')->name('admin.edit');
Route::get('admin/profile/edit/pic','admin\PhotoController@show')->name('change.pic.adminview');
Route::post('admin/profile/edit/pic','admin\PhotoController@edit')->name('change.pic.admin');
Route::get('admin/profile/change-password', 'admin\ChangePasswordController@index')->name('change.password.adminview');
Route::post('admin/profile/change-password', 'admin\ChangePasswordController@store')->name('change.password.admin');	

Route::get('admin/manage-category', 'admin\ManageCategoryController@index')->name('manage-category.index'); 
Route::resource('admin/manage-category', 'admin\ManageCategoryController');

Route::get('admin/settings', 'admin\SettingController@index')->name('settings.index'); 
Route::resource('admin/settings', 'admin\SettingController');

Route::get('admin/manage-statistics', 'admin\ManageStatisticsController@index')->name('manage-statistics.index'); 
Route::resource('admin/manage-statistics', 'admin\ManageStatisticsController');



Route::get('admin/statistics-clients', 'admin\StatisticsClientsController@index')->name('statistics-clients.index'); 
Route::resource('admin/statistics-clients', 'admin\StatisticsClientsController');
Route::get('admin/statistics-clients/{id}', 'admin\StatisticsClientsController@show ')->name('statistics-clients.index.filter'); 
Route::resource('admin/statistics-clients', 'admin\StatisticsClientsController');


Route::get('admin/statistics-booking', 'admin\StatisticsBookingController@index')->name('statistics-booking.index'); 
Route::resource('admin/statistics-booking', 'admin\StatisticsBookingController');

Route::get('admin/statistics-sale', 'admin\StatisticsSaleController@index')->name('statistics-sale.index'); 
Route::resource('admin/statistics-sale', 'admin\StatisticsSaleController');




Route::get('admin/subcategory', 'admin\SubCategoryController@index')->name('subcategory.index'); 
Route::get('admin/subcategory/card', 'admin\SubCategoryController@index_card')->name('subcategory.card'); 
Route::post('admin/subcategory/check', 'admin\SubCategoryController@check')->name('subcategory.check');
Route::get('createposts', 'admin\SubCategoryController@create');
Route::post('store', 'admin\SubCategoryController@store');
Route::post('destroy', 'admin\SubCategoryController@destroy');
Route::get('show', 'admin\SubCategoryController@show');
Route::get('admin/subcategory/{id}/translate', 'admin\SubCategoryController@translate')->name('subcategory.translate'); 
Route::resource('admin/subcategory', 'admin\SubCategoryController');


Route::get('admin/product', 'admin\ProductController@index')->name('product.index');
Route::get('admin/product/card', 'admin\ProductController@index_card')->name('product.card'); 

app/checkbox.php
<?php
 namespace App;
 use Illuminate\Database\Eloquent\Model;
 class postRoom extends Model
 {
     protected $fillable = [
     'title',
    ];
	
	
	    public function setCatAttribute($value)
    {
        $this->attributes['title'] = json_encode($value);
    }
  
    /**
     * Get the categories
     *
     */
    public function getCatAttribute($value)
    {
        return $this->attributes['title'] = json_decode($value);
    }
 }

app/Http/Controllers/CheckboxController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Session;
use App\checkbox;
use App\Product;

class CheckboxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $checkbox = Checkbox::all();
        return view('checkbox.index', compact('checkbox'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
                $product = Product::all();
                return view('checkbox.create', compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
	
 	
    	
	
public function store(Request $request) 
{
$checkbox = new Checkbox();
$checkbox->title = $request->has('title'); // Will set $article->title to true/false based on whether title exists in your input
// ...
$checkbox->save();

    return redirect('checkbox');
}

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $checkbox = Checkbox::find($id);

        return view('checkbox.show', compact('checkbox'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $checkbox = Checkbox::find($id);

        return view('section.edit', compact('checkbox'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=> 'required|max:255',
            'description'=> 'required|max:255'
			]);

        $checkbox = Checkbox::find($id);
        $checkbox->title = $request->get('title');
        $checkbox->description = $request->get('description');
        $checkbox->save();

        return redirect('checkbox.index')->with('success', 'Update with success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $checkbox = Checkbox::find($id);
        $checkbox->delete();

        return redirect('checkbox')->with('success', 'Record delete!');
    }
	
	
	
	
    public function countsection() 
   {
	  
	  $checkbox = DB::table('checkbox')
	  ->count('id');
        return view('checkbox.index', compact('checkbox'));
 
      
   }
}

resources/views/checkbox/create.blade.php
@extends('layout.layouttest')

@section('title', 'Changing the default title')
@section('content')


<div class="row">
<div class="col-lg-6 mx-auto">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
    @endif

    <form method="POST" action="{{ route('checkbox.store') }}">
     @csrf
<p>Sunday</p>
                <input type="checkbox" name="select-all-sunday" id="select-all-sunday" onclick="toggle(this);"> Check All
                <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-1" value="00:00"> 00:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-2" value="1"> 1:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-3" value="2"> 2:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-4" value="3:00"> 3:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-5" value="4:00"> 4:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-6" value="5:00"> 5:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-7" value="6:00"> 6:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-8" value="7:00"> 7:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-9" value="8:00"> 8:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-10" value="9:00"> 9:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-11" value="10:00"> 10:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-12" value="11:00"> 11:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-13" value="12:00"> 12:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-14" value="13:00"> 13:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-15" value="14:00"> 14:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-16" value="15:00"> 15:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-17" value="16:00"> 16:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-18" value="17:00"> 17:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-19" value="18:00"> 18:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-20" value="19:00"> 19:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-21" value="20:00"> 20:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-22" value="21:00"> 21:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-23" value="22:00"> 22:00 <br>
                <input type="checkbox" name="checkbox-sunday[]" id="checkbox-24" value="23:00"> 23:00 <br>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
</div>
@endsection

resources/views/checkbox/edit.blade.php
@extends('layouts.admin.dashbord')

@section('title', 'Changing the default title')
@section('content')
<div class="row titleapp">
<div class="col-md-7">
<span class="mt-4 pagetitle" >Edite Section</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a id="pagetitleprimerlink" href="{{ route('admindashboard') }}">Dashbord /</a>
<a id="pagetitleprimerlink" href="{{ route('section.index') }}">Section /</a>
<a id="pagetitlesecondelink">Edite</a>
</div>
</div>

<div class="row">
<div class="col-lg-6 mx-auto">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
    @endif

    <form method="POST" action="{{ route('section.update', $sections) }}">
     @csrf
     @method('PATCH') 
        <div class="form-group">
            <label for="post-title">Section</label>
            <input type="text" name="title" 
                   value="{{ $sections->title }}" class="form-control" id="post-title">
        </div>
        <div class="form-group">
            <label for="post-description">Description</label>
            <textarea name="description" class="form-control" id="post-description" rows="3">{{ $sections->description }}</textarea>
        </div>

        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div>
</div>
@endsection

resources/views/checkbox/index.blade.php
@extends('layout.layouttest')

@section('title', 'Changing the default title')
@section('content')


<a href="{{ route('checkbox.create') }}" class="btn btn-success">Add new</a>

 @if(session()->get('success'))
    <div class="alert alert-success mt-3">
      {{ session()->get('success') }}  
    </div>
@endif

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">checkbox</th>
      <th scope="col">Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
   @foreach($postRoom as $post)
    <tr>
      <th scope="row">{{ $post->id }}</th>
      <td>{{ $post->title }}</td>
      <td>{{ $post->description }}</td>
      <td class="table-buttons" style="text-align:right;">
        
        <form method="POST" action="{{ route('checkbox.destroy', $post) }}">
         <a href="{{ route('checkbox.show', $post) }}" class="btn btn-success">
          View
        </a>
        <a href="{{ route('checkbox.edit', $post) }}" class="btn btn-primary">
          Edite
        </a>@csrf
         @method('DELETE')
            <button type="submit" class="btn btn-danger">
              Delete
            </button>
        </form>
      </td>
    </tr>
  @endforeach
  </tbody>
</table>
@endsection

resources/views/checkbox/show.blade.php
@extends('layouts.admin.dashbord')

@section('title', 'Changing the default title')
@section('content')
<div class="row titleapp">
<div class="col-md-7">
<span class="mt-4 pagetitle" >Section details</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a id="pagetitleprimerlink" href="{{ route('admindashboard') }}">Dashbord /</a>
<a id="pagetitleprimerlink" href="{{ route('section.index') }}">Section /</a>
<a id="pagetitlesecondelink">Details</a>
</div>
</div>

<div class="card">
    <div class="card-body">
       <h3>{{ $sections->title }}</h3>
       <p>{{ $sections->description }}</p>
    </div>
</div>
@endsection