routes/web.php
Route::get('/test/Adomicile', 'Adomicile@index');
Route::get('/test/Check', 'Check@index');
Route::get('/test/Transfer', 'Transfer@index');


Route::get('/valide/{id}', 'Adomicile@update');
Route::post('/test/send', 'EmailController@send')->name('Admin.mail');
Route::get('admin/sendbox', 'EmailController@show')->name('Admin.send.mail');
Route::get('admin/sendbox/{Email}', 'EmailController@showmail');
Route::get('admin/trash', 'EmailController@showtrash')->name('Admin.trash');
Route::get('admin/destroy/{Email}', 'EmailController@destroy');
Route::get('admin/chat/', 'EmailController@chat')->name('chat.index');



Route::post('/test/payer', 'ProductsController@payer')->name('payer');

Route::get('/test/Strip', 'Strip@index');
Route::post('/charge','strip@charge');

Route::get('/test/Paypal', 'Paypal@paypal');
Route::get('/status', 'Paypal@status')->name('status');
Route::get('/canceled', 'Paypal@canceled')->name('canceled');

Route::get('/test', 'ProductsController@index');

Route::get('show/{id}','ProductsController@show')->name('store.show');
Route::get('cart', 'ProductsController@showCart')->name('cart');
Route::get('add-to-cart/{Product}', 'ProductsController@addToCart')->name('cart.add');;
Route::patch('update-cart', 'ProductsController@update');

Route::delete('remove-from-cart', 'ProductsController@remove');



Route::get('fr','web\fr\IndexController@index')->name('web.fr.index');
Route::get('de','web\de\IndexController@index')->name('web.de.index');
Route::get('en','web\en\IndexController@index')->name('web.en.index');

Route::get('products/{id}','ProductsController@products_seo')->name('products.seo');

Route::get('animation_caroucel', 'Animation@animation_caroucel');
Route::get('story', 'Animation@story');

Route::get('animation', 'Animation@index');
Route::get('animation_slider', 'Animation@slider');
Route::get('animation2', 'Animation@index2');
Route::get('animation3', 'Animation@index3');
Route::get('animation4', 'Animation@index4');
Route::get('animation5', 'Animation@index5');
Route::get('animation6', 'Animation@index6');
Route::get('animation7', 'Animation@index7');

Route::get('testcart', 'ProductsController@testcart');
Route::get('testcartlist', 'ProductsController@testcartlist')->name('testcartlist');

Route::get('change/{id}', 'ProductsController@listproduitdollar')->name('home.store.dolar');
Route::get('/', 'ProductsController@listproduit')->name('index.store');
Route::get('home', 'ProductsController@listproduit')->name('home.store');
Route::get('electronics', 'ProductsController@listproduit')->name('store.electronics');
Route::get('women', 'ProductsController@listproduit')->name('store.women');
Route::get('men', 'ProductsController@listproduit')->name('store.men');
Route::get('shop', 'ProductsController@listproduit')->name('store.shop.all');



Route::get('checkbox', 'MemberController@index')->name('checkbox.index');
Route::get('createposts', 'MemberController@create');
Route::post('store', 'MemberController@store');
Route::resource('checkbox', 'MemberController');

Route::get('checkboxtable','FrontpageController@home');
Route::post('/orders','OrderController@store');
Route::get('/orders','OrderController@index');
Route::post('store', 'OrderController@store')->name('order.store');
Route::get('/items/{id}','OrderController@items');

Route::get('/cart/details','user\CartdetailsController@index')->name('cart.details.user');
Route::post('/cart/details','user\CartdetailsController@edit')->name('cart.details.user.save');

Route::get('/cart/delivery/{id}','user\CartdeliveryController@index')->name('cart.delivery.user');
Route::post('/cart/delivery/{id}','user\CartdeliveryController@edit')->name('cart.delivery.user.save');



Route::get('/cart/payment/{id}','user\PaymentController@index')->name('cart.payment.user');
Route::post('/cart/payment/{id}','user\PaymentController@edit')->name('cart.payment.user.save');


Route::get('cart/login', 'UserLoginStoreController@index')->name('login.store');
Route::post('cart/login', 'UserLoginStoreController@postLogin')->name('user.login.store.save'); 

Route::get('login', 'UserLoginController@index')->name('login');
Route::post('login', 'UserLoginController@postLogin'); 

//registration routes
Route::get('registration', 'UserLoginController@registration')->name('user.registration');
Route::post('registration', 'UserLoginController@store')->name('user.registration.save'); 
Route::get('registrationedite', 'UserLoginController@registrationedite');
Route::post('registrationedite', 'UserLoginController@postregistrationedite'); 

//dashboard and logout route
Route::middleware('auth')->group(function(){
    Route::get('user', 'user\UserController@dashboard'); 
    Route::get('user/dashboard', 'user\UserController@dashboard')->name('user.dashboard'); 
    Route::get('user/profile', 'UserLoginController@profile')->name('user.profile');
    Route::get('user/logout', 'UserLoginController@logout');
    });
    
Route::get('user/request','user\OrderController@index')->name('user.request');
Route::get('user/request/show/{id}','user\OrderController@showrequest')->name('user.request.show');
Route::get('user/address', 'user\UserController@address')->name('user.address');

Route::get('user/edit','user\UserController@show')->name('user.edit');
Route::post('user/edit','user\UserController@edit')->name('user.edit.save');
Route::get('user/setting', 'user\UserController@setting')->name('user.setting'); 
Route::get('user/setting/change-password', 'user\ChangePasswordController@index')->name('change.password.view');
Route::post('user/setting/change-password', 'user\ChangePasswordController@store')->name('change.password');	
	
Route::get('user/setting/pic','user\PhotoController@show')->name('change.pic.view');
Route::post('user/setting/pic','user\PhotoController@edit')->name('change.pic');
	
Route::get('admin/stape1', 'AdminLoginController@stape1')->name('login.admin.stape1');

Route::get('admin', 'AdminLoginController@index')->name('login.admin');
Route::post('admin/varification', 'AdminLoginController@stape2')->name('login.admin.stape2');
	
Route::get('admin', 'AdminLoginController@index')->name('login.admin');
Route::post('admin', 'AdminLoginController@postLogin')->name('saveadminlogin'); 


Route::middleware('auth')->group(function(){
Route::get('admin/home', 'admin\AdminController@dashboard')->name('home'); 
Route::get('admin/homes', 'admin\AdminController@dashboards')->name('homes'); 


Route::post('admin/logout', 'AdminLoginController@logout')->name('logout'); 
});
//Admin profile
Route::get('admin/profile', 'admin\ProfileController@profile')->name('admin.profile');
Route::get('admin/profile/edit','admin\ProfileController@show')->name('admin.edit.profile');
Route::post('admin/profile/edit','admin\ProfileController@edit')->name('admin.edit');
Route::get('admin/profile/edit/pic','admin\PhotoController@show')->name('change.pic.adminview');
Route::post('admin/profile/edit/pic','admin\PhotoController@edit')->name('change.pic.admin');
Route::get('admin/profile/change-password', 'admin\ChangePasswordController@index')->name('change.password.adminview');
Route::post('admin/profile/change-password', 'admin\ChangePasswordController@store')->name('change.password.admin');	

Route::get('admin/manage-category', 'admin\ManageCategoryController@index')->name('manage-category.index'); 
Route::resource('admin/manage-category', 'admin\ManageCategoryController');

Route::get('admin/settings', 'admin\SettingController@index')->name('settings.index'); 
Route::resource('admin/settings', 'admin\SettingController');

Route::get('admin/manage-statistics', 'admin\ManageStatisticsController@index')->name('manage-statistics.index'); 
Route::resource('admin/manage-statistics', 'admin\ManageStatisticsController');



Route::get('admin/statistics-clients', 'admin\StatisticsClientsController@index')->name('statistics-clients.index'); 
Route::resource('admin/statistics-clients', 'admin\StatisticsClientsController');
Route::get('admin/statistics-clients/{id}', 'admin\StatisticsClientsController@show ')->name('statistics-clients.index.filter'); 
Route::resource('admin/statistics-clients', 'admin\StatisticsClientsController');


Route::get('admin/statistics-booking', 'admin\StatisticsBookingController@index')->name('statistics-booking.index'); 
Route::resource('admin/statistics-booking', 'admin\StatisticsBookingController');

Route::get('admin/statistics-sale', 'admin\StatisticsSaleController@index')->name('statistics-sale.index'); 
Route::resource('admin/statistics-sale', 'admin\StatisticsSaleController');




Route::get('admin/subcategory', 'admin\SubCategoryController@index')->name('subcategory.index'); 
Route::get('admin/subcategory/card', 'admin\SubCategoryController@index_card')->name('subcategory.card'); 
Route::post('admin/subcategory/check', 'admin\SubCategoryController@check')->name('subcategory.check');
Route::get('createposts', 'admin\SubCategoryController@create');
Route::post('store', 'admin\SubCategoryController@store');
Route::post('destroy', 'admin\SubCategoryController@destroy');
Route::get('show', 'admin\SubCategoryController@show');
Route::get('admin/subcategory/{id}/translate', 'admin\SubCategoryController@translate')->name('subcategory.translate'); 
Route::resource('admin/subcategory', 'admin\SubCategoryController');


Route::get('admin/product', 'admin\ProductController@index')->name('product.index');
Route::get('admin/product/card', 'admin\ProductController@index_card')->name('product.card'); 
Route::post('admin/product/check', 'admin\ProductController@check')->name('product.check');
Route::get('create', 'admin\ProductController@create');
Route::post('store', 'admin\ProductController@store');
Route::post('destroy', 'admin\ProductController@destroy');
Route::get('show', 'admin\ProductController@show');
Route::resource('admin/product', 'admin\ProductController');
Route::post('admin/product/store_category/{id}', 'admin\ProductController@store_category')->name('product.store_category');

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use DB;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Session;

use App\User;

use Response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
		if(Auth::check()){
				 
		$notifications = DB::table('notifications')
		->where('status', '=', "0")
        ->get();
		  
		   $data['Users'] = DB::table('users')
	      ->get();

	   	
        $userscount = DB::table('users')
        ->count('id');
		
        return view('admin.user.index',$data, compact('userscount', 'notifications'));
		}
	    
		return redirect::to("admin");

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function stores(Request $request)
    {
        //
		
        $postID = $request->post_id;
        $post   =   Manage_document::updateOrCreate(['id' => $postID],
		
		
                    ['id_client' => $request->id_client, 'title' => $request->title, 'fichier' => $request->fichier, 'note' => $request->note, 'id_admin' => $request->id_admin, 'id_day' => $request->id_day, 'id_month' => $request->id_month, 'month' => $request->month, 'id_year' => $request->id_year]);
    
        return Response::json($post);
    }
	
	
	    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=> 'required|max:255',
            'parent_id'=> 'required|max:255',
            'active'=> 'required|max:255'
		  ]);

      $Category= new Category([
            'name' => $request->get('name'),
            'parent_id' => $request->get('parent_id'),
            'active' => $request->get('active'),
        ]);
		
      $Category->save();

      return redirect::route('category.index')->with('success', 'Create with success!');
  
    }
	
	public function edit($id)
    {
        if(Auth::check())
		{
       $Category = Category::find($id);

 
        return view('admin.category.edit', compact('Category'));
		}
		return redirect::to("admin");

    }
	
	
	
	public function update(Request $request, $id)
    {
        $request->validate([
            'status'=> 'required|max:2055',
			'image' =>'required',
			]);

       
		
        $User = User::find($id);
        $User->status = $request->get('status');
        $User->save();

        return redirect::to('admin/user/'.$id.'')->with('success', 'Update with success!');
    }


	


	
	public function show($id)
    {
        
		if(Auth::check()){
				 
        $notifications = DB::table('notifications')
		->where('status', '=', "0")
        ->get();

		
		$User = User::find($id);

	 
	 

        return view('admin.user.show', compact('User', 'notifications'));
		}
	    
		return redirect::to("admin");

    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
	 
	 public function destroy($id)
    {
        //
        $post = Category::where('id',$id)->delete();
   
        return Response::json($post);
    }
}

app/Http/Controllers/user/CartdeliveryController.php
<?php
namespace App\Http\Controllers\user;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Validator,Redirect,Response;
use DB;
use App\Product;
use Cart;
use App\Category;
use App\Orders;
use App\Items;
use Session;


class CartdeliveryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
         if(Auth::check()){
	    $datas['Category'] = Category::where('parent_id',0)
		->where('parent_id', '=', "0")
        ->get();
		
		
		$Orders = DB::table('orders')
		->where('id', '=', "".$id."")
        ->get();
        
	    $Items = DB::table('items')
		->where('orders_id', '=', "".$id."")
        ->count('id');
		
		
	   $Product = DB::table('products')
       ->join('items', 'products.id', '=', 'items.product_name')
       ->join('orders', 'items.orders_id', '=', 'orders.id')
       ->select('products.product_name', 'products.photo', 'products.product_price', 'orders.currency', 'items.quantity', 'items.id')
       ->get();
	   
        return view('user.cart_details.delivery',$datas,compact('Items','Product','Orders'));
		 }
      return redirect::route('index.store');

    }





 public function edit(Request $request) 
   {
      $id_order = $request->input('id_order');
      $delivery = $request->input('delivery');
      $updated_at = $request->input('updated_at');
      DB::update('update orders set delivery = ?, updated_at = ? where id = ?',[$delivery,$updated_at,$id_order]);
      return redirect('cart/payment/'.$request->input('id_order').'')->with('success', 'Update with success!');

   }
    
}

app/Http/Controllers/user/CartdetailsController.php
<?php
namespace App\Http\Controllers\user;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Validator,Redirect,Response;
use DB;
use App\Product;
use Cart;
use App\Category;
use App\Orders;
use App\Items;
use Session;


class CartdetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
  
    public function index()
    {
	   
        if (session()->has('cart')) {
            $cart = new Cart(session()->get('cart'));
        } else {
            $cart = null;
        }

        return view('user.cart_details.index',compact('cart'));
		 }




 public function edit(Request $request) 
   {
      $id_order = $request->input('id_order');
      $firstname = $request->input('firstname');
      $lastname = $request->input('lastname');
      $tel = $request->input('tel');
      $mobile = $request->input('mobile');
      $country = $request->input('country');
      $city = $request->input('city');
      $address = $request->input('address');
      $postcode = $request->input('postcode');
      $updated_at = $request->input('updated_at');
      DB::update('update users set firstname = ?, lastname = ?, tel = ?, mobile = ?, country = ?, city = ?, address = ?, postcode = ?, updated_at = ? where id = ?',[$firstname,$lastname,$tel,$mobile,$country,$city,$address,$postcode,$updated_at,ucfirst(Auth()->user()->id)]);
      return redirect('cart/delivery/'.$request->input('id_order').'')->with('success', 'Update with success!');

   }
    
}

app/Http/Controllers/user/ExerciceController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use DB;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Session;
use App\exercise;


class ExerciceController extends Controller 
{
   public function index() 
   {
	  
      if(Auth::check()){
	    
		$exercise = DB::table('exercises')
	    ->where('section', '=', "".ucfirst(Auth()->user()->section)."")

       ->join('sections', 'exercises.section', '=', 'sections.id')
       ->select('exercises.exercise_name', 'exercises.id', 'exercises.description', 'exercises.created_at', 'exercises.fichier', 'sections.title')
       ->get();
	   
		
		$exercisecount = DB::table('exercises')
			    ->where('section', '=', "".ucfirst(Auth()->user()->section)."")

	    ->count('id');
		
        return view('userexercice.index', compact('exercise', 'exercisecount'));
		
		
      }
      
   }


}

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')
@section('title', 'Manage category')
@section('content')
<div class="container">
<div class="row titleapp">
<div class="col-md-7">
<span class="mt-4 pagetitle" >Manage category</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a id="pagetitleprimerlink" href="{{ route('home') }}">Dashbord /</a>
<a id="pagetitlesecondelink">Category</a>
</div>
</div>


<div class="space"></div>
<div class="space"></div>




<div class="row cadre_add" style="padding:10px 0px 5px 0px;">
<div class="col-md-7">
<span class="mt-4 pagetitle" >Category</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a href="{{ route('category.index') }}" class="btn btn-success mb-2" id="create-new-post">Back to list</a> 
</div>
</div>


  <div class="space"></div>
  <div class="space"></div>

<div class="row">
<div class="col-lg-12 mx-auto"  style="padding:0px;">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
    @endif




<div class="Individual cadre_add">
<form action = "{{ route('category.update', $Category->id) }}" method = "POST">
@csrf
@method('PATCH') 

<input type="hidden" name="image" value="0c3b3adb1a7530892e55ef36d3be6cb8.png" />
<input type="hidden" name="type" value="1" />
<input type="hidden"name="company_name" value="0"/>
<div class="row">
<h3 class="page-title2" >Category details</h3>



<div class="form-group col-md-6">
<label for="manage_client-description" class="textblod">Name</label>
<input type="text" name="name" class="form-control" value="{{$Category->name}}" />
</div>





<div class="form-group col-md-6">
<label for="post-description" style="width:100%;" class="textblod">Activation</label>
<label for="r2" class="textnormal">
<input type="radio" name="active" id="r2"onClick="getResults()" value="1" 
@if($Category->active == 1)
checked  
@else
@endif > Active
</label>

<label for="r1" class="textnormal" style="margin-left:20px;">
<input type="radio" name="active" id="r1" onClick="getResults()" value="0"
@if($Category->active == 0)
checked  
@else
@endif> Blocked
</label>		
</div>




</div>


<div class="modal-footer"style="text-align:right;">
<a href="{{ route('category.index') }}" class="model_btn_close">Cancel</a>
<button type="submit" class="model_btn_save">Save</button>
</div>
</form>
</div>

  
 
  





		

</div>
</div>
</div>
</br>


@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('title', 'Manage user')
@section('content')
<script src="{{ asset('public/ajax/libs/jquery.validate.js')}}"></script>




<div class="container">
<div class="row titleapp">
<div class="col-md-7">
<span class="mt-4 pagetitle" >Manage user</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a id="pagetitleprimerlink" href="{{ route('home') }}">Dashbord /</a>
<a id="pagetitlesecondelink">user</a>
</div>
</div>


<div class="space"></div>
<div class="space"></div>




<div class="row cadre_add" style="padding:10px 0px 5px 0px;">
<div class="col-md-7">
<span class="mt-4 pagetitle" >User ( {{ $userscount }} )</span>
</div>
<div class="col-md-5" style="text-align:right;">
<a href="{{ route('category.create') }}" class="btn-switch" title="Excel"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a> 
<a href="{{ route('category.create') }}" class="btn-switch" title="PDF"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a> 
</div>
</div>
<div class="space"></div>
<div class="space"></div>





<div class="row">
<div class="col-12">
@if(session()->get('success'))
<div class="alert alert-success mt-3">
{{ session()->get('success') }}  
</div>
@endif



<table id="example" class="table table-striped table-bordered" style="width:100%">
<thead>
<tr>
<th>Name</th>
<th>Role</th>
<th>Email</th>
<th>Date</th>
<th style="text-align:center;">Etat</th>
<th></th>
</tr>
</thead>
<tbody id="posts-crud">
@foreach($Users as $post)
<div class="modal fade" id="exampleModal{{ $post->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body" style="text-align:center;">
	          <h5 id="exampleModalLabel" class="textbloddelete">Delete ?</h5>
	          <h5 id="exampleModalLabel" class="textnormaldelete ">Please ensure and then confirm!</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="model_btn_close" data-dismiss="modal">No, cancel</button>
		<a  href="javascript:void(0)" id="delete-post" data-id="{{ $post->id }}" class="model_btn_delete delete-post" data-dismiss="modal">Yes, Delete</a>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal{{ $post->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body" style="text-align:center;">
	          <h5 id="exampleModalLabel" class="textbloddelete">Delete ?</h5>
	          <h5 id="exampleModalLabel" class="textnormaldelete ">Please ensure and then confirm!</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="model_btn_close" data-dismiss="modal">No, cancel</button>
		<a  href="javascript:void(0)" id="delete-post" data-id="{{ $post->id }}" class="model_btn_delete delete-post" data-dismiss="modal">Yes, Delete</a>
      </div>
    </div>
  </div>
</div>

<tr id="post_id_{{ $post->id }}">
<td>{{ $post->firstname  }} {{ $post->lastname  }}</td>
<td>
@if($post->role =='2')
<span class="">Super admin</span>
@elseif($post->role =='1')
<span class="">Admin</span>
@else
<span class="">User</span>
@endif
</td>
<td>{{ $post->email  }}</td>
<td>{{ $post->created_at  }}</td>
<td style="text-align:center;">
@if($post->status =='1')
<span class="active_back">active</span>
@else
<span class="blocked_back">blocked</span>
@endif
</td>
<td class="td_btn">
<a href="{{ route('user.show', $post->id) }}" class="btn-delete"><i class="fa fa-eye"></i></a>
</td>
</tr>
@endforeach
</tbody>
</table>        

       </div> 
    </div>
</div>

<div class="modal fade" id="ajax-crud-modal" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title" id="postCrudModal"></h4>
				<button type="button" class="close model_fa_close" data-dismiss="modal">&times;</button>

    </div>

	
	
<form action="{{ route('category.store') }}" method="post" accept-charset="utf-8" enctype="multipart/form-data">
     @csrf
	 <div class="modal-body">

<input type="hidden" name="active" id="active" value="1">
<input type="hidden" name="parent_id" id="parent_id" value="0">


<input type="hidden" name="id_admin" id="id_admin" value="{{ Auth::user()->id }}">
<input type="hidden" name="post_id" id="post_id">
<div class="form-group form-group-max" style="height:70px;">
<label for="title" class="textblod">Title</label>
<input name="name" id="name" class="form-control" style="height:40px;" required />
</div>

</div>
<div class="modal-footer"style="text-align:right;">
<button type="button" class="model_btn_close" data-dismiss="modal">Close</button>
<button type="submit" class="model_btn_save" id="btn-save" value="create">Save</button>
</div>
</form>

</div>
</div>
</div>



<script>
  $(document).ready(function () {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $('#create-new-post').click(function () {
        $('#btn-save').val("create-post");
        $('#postForm').trigger("reset");
        $('#postCrudModal').html("Add New Category");
        $('#ajax-crud-modal').modal('show');
    });
 
    $('body').on('click', '#edit-post', function () {
      var post_id = $(this).data('id');
      $.get(+post_id+'/edit', function (data) {
         $('#postCrudModal').html("Edit Documents");
          $('#btn-save').val("edit-post");
          $('#ajax-crud-modal').modal('show');
          $('#post_id').val(data.id);
          $('#id_client').val(data.id_client);
          $('#crm_type').val(data.crm_type);
		  
		          
		  
          $('#title').val(data.title);
          $('#fichier').val(data.fichier);
          $('#crm_date').val(data.crm_date);  
          $('#crm_time').val(data.crm_time);  
          $('#note').val(data.note);  
          $('#id_admin').val(data.id_admin);  
          $('#id_day').val(data.id_day);  
          $('#id_month').val(data.id_month);  
          $('#month').val(data.month);  
          $('#id_year').val(data.id_year);  
      })
   });

    $('body').on('click', '.delete-post', function () {
        var post_id = $(this).data("id");		
		
		
		
		

 
        $.ajax({
            type: "DELETE",
            url: "{{ url('admin/category')}}"+'/'+post_id,
            success: function (data) {
                $("#post_id_" + post_id).remove();
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
    });   
  });
 
 if ($("#postForm").length > 0) {
      $("#postForm").validate({
 
     submitHandler: function(form) {

      var actionType = $('#btn-save').val();
      $('#btn-save').html('Sending..');


      $.ajax({
          data: $('#postForm').serialize(),
          url: "{{ route('category.store') }}",
        
          type: "POST",
          dataType: 'json',
          success: function (data) {
              var post = '<tr id="post_id_' + data.id + '"><td>' + data.crm_type + '</td><td>' + data.title + ' </td><td>' + data.crm_date + ' ' + data.crm_time + '</td><td>' + data.month + '</td>';
              post += '<td class="td_btn"><a href="{{ url("clients/documents") }}/' + data.id_client + '/' + data.id + '" class="btn-edite"><i class="fa fa-eye"></i></a> <a href="javascript:void(0)" id="edit-post" data-id="' + data.id + '" class="btn-edite"><i class="fa fa-edit"></i></a> <a href="javascript:void(0)" id="delete-post" data-id="' + data.id + '" class="btn-delete delete-post"><i class="fa fa-trash"></i></a></td></tr>';
              post += '';
               
              
              if (actionType == "create-post") {
                  $('#posts-crud').prepend(post);
              } else {
                  $("#post_id_" + data.id).replaceWith(post);
              }
 
              $('#postForm').trigger("reset");
              $('#ajax-crud-modal').modal('hide');
              $('#btn-save').html('Save Changes');
              
          },
          error: function (data) {
              console.log('Error:', data);
              $('#btn-save').html('Save Changes');
          }
      });
    }
  })
}
</script>


<script>
$(document).ready(function () {
    $(".Call").hide();
    $("#r1").click(function () {
        $(".Call").show();
    });
	
    $("#r2").click(function () {
        $(".Call").hide();
    });
	
	$(".Visit").hide();
    $("#r1").click (function () {
        $(".Visit").hide();
    });
	
    $("#r2").click(function () {
        $(".Visit").show();
    });
});
</script>










 

<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

 
@endsection